### ISSUE TITLE
No build updates on F-Droid

### ISSUE THREAD

**Issue by dupondje** [stefan-niedermann/nextcloud-deck#140]
Nice to see there have been many improvements on the app the latest weeks.
But the updated releases are not pushed to F-Droid.

Can this be checked? Or eventually build APK here?

**Comment by desperateCoder** [comment]
Hi @dupondje, this is funny, since we are also waiting for F-Droid to recognize our releases...

We actually have no clue whats wrong currently, and i have no idea what to do about that. Maybe @stefan-niedermann could dig into this, but afaik he es as clueless as i am.

Here is the current master (22.09.2019, about 14:00).
**ATTENTION:**
Github won't let me upload APKs here, so i renamed it to zip. please rename it back to .apk to install it on your phone. 
[app-debug.zip](https://github.com/stefan-niedermann/nextcloud-deck/files/3640027/app-debug.zip)

**Comment by dupondje** [comment]
Seems to build fine on F-Droid, but then it's stuck somewhere:
https://f-droid.org/wiki/index.php?title=it.niedermann.nextcloud.deck/lastbuild_8&redirect=no

**Comment by AndyScherzinger** [comment]
Publishing is done manually by members of the f-droid team which takes an undefined amount of time, you'd have to ping folks like @Bubu to take a look

**Comment by stefan-niedermann** [comment]
@Bubu i thought this would be done automatically when the build was successful. Shall we ping you every time we do a release?

**Comment by Bubu** [comment]
AFAIK there just wasn't an index update since the app got built? But I justarrived back from vacation, so I'm not sure...

**Comment by stefan-niedermann** [comment]
0.0.8 is available on F-Droid, so i guess this issue is solved :)

Thanks for @Bubu if there was more to do  except being patient and waiting for an index update <3

**Comment by nr458h** [comment]
I'm afraid, this issue is not solved. We are again two releases behind

**Comment by stefan-niedermann** [comment]
Well, F-Droid does not fetch every release. They update their index periodically only all few days. So if we are doing multiple releases within one day, F-Droid will update their index only some days later and publish the latest version.

@Bubu maybe you can tell us if this assumption is correct or if we need to open an issue in the `fdroiddata`-repo on gitlab?

**Comment by Bubu** [comment]
This is correct, AFAIK.

**Comment by nr458h** [comment]
ok, thanks for the explanation ;)

**Comment by nr458h** [comment]
As I m waiting patient for the dark theme - version hit the f-droid store. I just want to inform you, that version 0.0.10 is still not available. Sorry for the annoying pinning of this topic ☺️

**Comment by stefan-niedermann** [comment]
Seems like F-Droid data already fetched version 10: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/it.niedermann.nextcloud.deck.yml

```
CurrentVersion: 0.0.10
CurrentVersionCode: 10
```

The tag has been created 15 days ago, this seems indeed be way too long for an index update.

@Bubu maybe you could have another look? Let me know how i can help you.

**Comment by stefan-niedermann** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1753#note_229643978

**Comment by IzzySoft** [comment]
Tag was detected and build block added, but [build fails](https://f-droid.org/wiki/page/it.niedermann.nextcloud.deck/lastbuild_10). I'm neither Android dev nor do I have build experience, so that's all I can do: pointing to that log…

**Comment by stefan-niedermann** [comment]
That's the info that was missing! Thank you. I guess we have to add 

```
android {
      lintOptions {
          checkReleaseBuilds false
          // Or, if you prefer, you can continue to check for errors in release builds,
          // but continue the build even when errors are found:
          abortOnError false
      }
  }
```

to the build.gradle-file. I remember that i had to do that with the notes app, too but i am wonderung how any previous version could land in F-Droid :D

I am currently not on PC, maybe @desperateCoder can fix this quickly or i will try to fix it tomorrow.

Thanks @IzzySoft !

**Comment by stefan-niedermann** [comment]
I think the next tagged version will not abort the build now anymore when translations are missing.

I will keep an eye on the F-Droid build an reopen in case i missed something.

**Comment by IzzySoft** [comment]
Glad I could help! Always a good idea to [take a look at the build logs](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&hidebots=0&days=30&limit=500) :wink: Just bookmark that link :rofl:

**Comment by stefan-niedermann** [comment]
Yes, we are aware that 0.0.13 is not a:

**Comment by licaon-kter** [comment]
@stefan-niedermann Some help, build 19 fails with:
```
==== detail begin ====
Found 5.4.1 via distributionUrl
Running /home/strech/.cache/fdroidserver/gradle/5.4.1/bin/gradle assembleRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.21}.
     Required by:
         project :app
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'androidx.room:room-testing:2.2.3' --> 'androidx.room:room-migration:2.2.3' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.41'
           Constraint path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.21}' because of the following reason: debugRuntimeClasspath uses version 1.3.21
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'com.github.skydoves:colorpickerpreference:2.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.21}.
     Required by:
         project :app
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints:
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'androidx.room:room-testing:2.2.3' --> 'androidx.room:room-migration:2.2.3' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.41' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.3.41'
           Constraint path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.21}' because of the following reason: debugRuntimeClasspath uses version 1.3.21

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.41.
     Required by:
         project :app > androidx.room:room-testing:2.2.3 > androidx.room:room-migration:2.2.3
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'androidx.room:room-testing:2.2.3' --> 'androidx.room:room-migration:2.2.3' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.41'
           Constraint path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.21}' because of the following reason: debugRuntimeClasspath uses version 1.3.21
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'com.github.skydoves:colorpickerpreference:2.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.3.21.
     Required by:
         project :app > org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'androidx.room:room-testing:2.2.3' --> 'androidx.room:room-migration:2.2.3' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.41'
           Constraint path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.21}' because of the following reason: debugRuntimeClasspath uses version 1.3.21
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'com.github.skydoves:colorpickerpreference:2.0.0' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.21'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:1.3.41.
     Required by:
         project :app > org.jetbrains.kotlin:kotlin-stdlib:1.3.41
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints:
           Dependency path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'androidx.room:room-testing:2.2.3' --> 'androidx.room:room-migration:2.2.3' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.3.41' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.3.41'
           Constraint path 'it.niedermann.nextcloud.deck:app:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.21}' because of the following reason: debugRuntimeClasspath uses version 1.3.21


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
```
...what am I missing?
